version: "3.7"
services:
    flaskapp:
        image: flaskapp
        ports:
            - 5001:5000
        environment:
            SQLALCHEMY_DATABASE_URI: 'postgresql://postgres:root@postgres:5432/coursedb'
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5
      volumes:
           - postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      restart: on-failure

    graphql-engine:
        image: hasura/graphql-engine
        ports:
        - "8085:8080"
        depends_on:
        - "postgres"
        restart: on-failure
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@postgres:5432/coursedb
        command:
            - graphql-engine
            - serve
            - --enable-console

volumes:
    postgres:
